// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWAFa07XuLQwnZ54RwnsyZHr29Fy7voc',
    appId: '1:98334600210:web:97921ba5f139818f79fccb',
    messagingSenderId: '98334600210',
    projectId: 'instagram-clone-f0b1f',
    authDomain: 'instagram-clone-f0b1f.firebaseapp.com',
    storageBucket: 'instagram-clone-f0b1f.appspot.com',
    measurementId: 'G-RBN79CGX6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2LVoIvqvEk_w0FAqnQ9NFOXpZYP75f0',
    appId: '1:98334600210:android:666397725a949f2d79fccb',
    messagingSenderId: '98334600210',
    projectId: 'instagram-clone-f0b1f',
    storageBucket: 'instagram-clone-f0b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJ_7DARAr_l6np05UIjsRerGZ0I_3n_8',
    appId: '1:98334600210:ios:f72d85617b3ab1fc79fccb',
    messagingSenderId: '98334600210',
    projectId: 'instagram-clone-f0b1f',
    storageBucket: 'instagram-clone-f0b1f.appspot.com',
    iosClientId: '98334600210-4p9p8lu3hrvuca4g49mms11pdg049foj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJ_7DARAr_l6np05UIjsRerGZ0I_3n_8',
    appId: '1:98334600210:ios:f72d85617b3ab1fc79fccb',
    messagingSenderId: '98334600210',
    projectId: 'instagram-clone-f0b1f',
    storageBucket: 'instagram-clone-f0b1f.appspot.com',
    iosClientId: '98334600210-4p9p8lu3hrvuca4g49mms11pdg049foj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
